// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Econorte.Services.Data;

public partial class Econorte_Context : DbContext
{
    public Econorte_Context(DbContextOptions<Econorte_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Sensors> Sensors { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.Id_Role).HasName("PK_ROLES");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<Sensors>(entity =>
        {
            entity.HasKey(e => e.Id_Sensor);

            entity.Property(e => e.Date)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.fk_UserNavigation).WithMany(p => p.Sensors)
                .HasForeignKey(d => d.fk_User)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SENSORS_USERS");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id_User).HasName("PK_USERS");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.Email)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.LastLog).HasColumnType("date");
            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Phone).IsUnicode(false);

            entity.HasOne(d => d.fk_RoleNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_Role)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_USERS_ROLES");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}