// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.Services.Data;

public partial class Roles
{
    public int Id_Role { get; set; }

    public string Name { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}