// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.Services.Data;

public partial class SensorsParameters
{
    public int Id_Parameters { get; set; }

    public int fk_Sensor { get; set; }

    public DateTime? Date { get; set; }

    public double? Temperature { get; set; }

    public double? Humidity { get; set; }

    public int? Gas_Level { get; set; }

    public int? Vibration { get; set; }

    public bool? Earthquake_Status { get; set; }

    public bool? Fire_Status { get; set; }

    public virtual Sensors fk_SensorNavigation { get; set; }
}