// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.Services.Data;

public partial class Sensors
{
    public int Id_Sensor { get; set; }

    public string Name { get; set; }

    public int fk_User { get; set; }

    public virtual ICollection<SensorsParameters> SensorsParameters { get; set; } = new List<SensorsParameters>();

    public virtual Users fk_UserNavigation { get; set; }
}