// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.Services.Data;

public partial class Sensors
{
    public int Id_Sensor { get; set; }

    public string Name { get; set; }

    public DateTime? Date { get; set; }

    public double? Temperature { get; set; }

    public double? Humidity { get; set; }

    public int? Gas_Level { get; set; }

    public int? Vibration { get; set; }

    public bool? Earthquake_Status { get; set; }

    public bool? Fire_Status { get; set; }

    public byte? Alarm_Intensity { get; set; }

    public int fk_User { get; set; }

    public virtual Users fk_UserNavigation { get; set; }
}