// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.Services.Data;

public partial class Users
{
    public int Id_User { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public int fk_Role { get; set; }

    public bool Active { get; set; }

    public bool Login { get; set; }

    public DateTime? LastLog { get; set; }

    public virtual ICollection<Sensors> Sensors { get; set; } = new List<Sensors>();

    public virtual Roles fk_RoleNavigation { get; set; }
}