CREATE DATABASE Econorte_Dev;
USE Econorte_Dev;

--Roles
CREATE TABLE Roles 
(
	Id_Role INT IDENTITY NOT NULL CONSTRAINT PK_ROLES PRIMARY KEY,
	[Name] VARCHAR (MAX) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
);

--Usuarios
CREATE TABLE Users 
(
	Id_User INT IDENTITY NOT NULL CONSTRAINT PK_USERS PRIMARY KEY,
	[Name] VARCHAR(MAX) NOT NULL,
	Email VARCHAR(MAX) NOT NULL,
	[Password] VARCHAR(MAX) NOT NULL,
	Phone VARCHAR (MAX) NULL,
	fk_Role INT NOT NULL CONSTRAINT FK_USERS_ROLES FOREIGN KEY REFERENCES Roles(Id_Role),
	Active BIT NOT NULL DEFAULT 1,
	[Login] BIT NOT NULL DEFAULT 0,
	LastLog DATE NULL
);

--Roles
INSERT INTO [Roles] (Name) VALUES
('Admin'),
('Public');