services:
  econorte.services:
    image: econorte.services:dev
    build:
      context: .
      dockerfile: Econorte.Services/Dockerfile
    ports:
      - "32771:8080"
      - "32772:8081"
    volumes:
      - ./Econorte.Services/:/app/Econorte.Services
  econorte.website:
    image: econorte.website:dev
    build:
      context: .
      dockerfile: Econorte.WebSite/Dockerfile
    ports:
      - "32769:8080"
      - "32770:8081"
    volumes:
      - ./Econorte.Website/:/app/Econorte.Website
    depends_on:
      - econorte.services
  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: econorte.sqlexpress
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - econorte-sql:/var/opt/mssql
    restart: always

volumes:
  econorte-sql: