// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.WebSite.Data;

public partial class APIs
{
    public int Id_API { get; set; }

    public string Name { get; set; }

    public string URL_Dev { get; set; }

    public string URL_Prod { get; set; }

    public int fk_Method { get; set; }

    public virtual Methods fk_MethodNavigation { get; set; }
}