// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Econorte.WebSite.Data;

public partial class Econorte_DevContext : DbContext
{
    public Econorte_DevContext(DbContextOptions<Econorte_DevContext> options)
        : base(options)
    {
    }

    public virtual DbSet<APIs> APIs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<APIs>(entity =>
        {
            entity.HasKey(e => e.Id_API);

            entity.Property(e => e.Name)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.URL_Dev)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.URL_Prod)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}