// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Econorte.WebSite.Data;

public partial class Methods
{
    public int Id_Method { get; set; }

    public string Name { get; set; }

    public virtual ICollection<APIs> APIs { get; set; } = new List<APIs>();
}